[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "erc6551/=lib/reference/src/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
pentagon = "https://rpc.pentagon.games"
